package drupal

import (
	"encoding/json"
	"os"
	"strconv"
	"testing"
)

// The PHP implementation is the specification.
//
// It is the one that has been run against real drupal.org and GitLab data, so
// the port is held to its answers case by case rather than to a reading of
// what it ought to do. corpus.json is generated by testdata_gen.php.
type corpus struct {
	Intersects []struct {
		Constraint string `json:"constraint"`
		Core       string `json:"core"`
		Applies    bool   `json:"applies"`
	} `json:"intersects"`
	Stability map[string]string `json:"stability"`
}

func load(t *testing.T, path string) (corpus, bool) {
	t.Helper()

	raw, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return corpus{}, false
	}
	if err != nil {
		t.Fatalf("reading %s: %v", path, err)
	}

	var c corpus
	if err := json.Unmarshal(raw, &c); err != nil {
		t.Fatalf("parsing %s: %v", path, err)
	}

	return c, true
}

func check(t *testing.T, c corpus) {
	t.Helper()

	for _, row := range c.Intersects {
		core, err := strconv.Atoi(row.Core)
		if err != nil {
			t.Fatalf("corpus holds a non-numeric core %q", row.Core)
		}

		got, err := Applies(row.Constraint, core)
		if err != nil {
			t.Errorf("%-30s core %-2s  php=%-5v go=error(%v)", row.Constraint, row.Core, row.Applies, err)
			continue
		}
		if got != row.Applies {
			t.Errorf("%-30s core %-2s  php=%-5v go=%v", row.Constraint, row.Core, row.Applies, got)
		}
	}
}

func TestAppliesMatchesComposerSemver(t *testing.T) {
	c, ok := load(t, "../../corpus.json")
	if !ok {
		t.Fatal("corpus.json is missing; run `php testdata_gen.php`")
	}
	if len(c.Intersects) == 0 {
		t.Fatal("corpus.json holds no intersection cases")
	}

	check(t, c)
	t.Logf("%d cases from composer/semver", len(c.Intersects))
}

// Random constraints, because real ones are not adversarial.
//
// Every core_version_requirement in the wild is a caret, so they exercise one
// shape. 2,703 random ones found a case the real corpus could not: composer
// reads a bare "7.8" as the exact version 7.8.0, not as the range 7.8.x, which
// makes "7.8 7" two pins that can never both hold.
//
// Skipped when the corpus has not been generated — it is large and derived, so
// it is not committed.
func TestAppliesAgainstRandomConstraints(t *testing.T) {
	c, ok := load(t, "../../corpus-fuzz.json")
	if !ok {
		t.Skip("no corpus-fuzz.json; run `php testdata_gen.php --fuzz=20000`")
	}

	check(t, c)
	t.Logf("%d random cases from composer/semver", len(c.Intersects))
}

// Held to composer's own VersionParser::parseStability.
func TestStabilityMatchesComposerSemver(t *testing.T) {
	c, ok := load(t, "../../corpus.json")
	if !ok {
		t.Fatal("corpus.json is missing; run `php testdata_gen.php`")
	}
	if len(c.Stability) == 0 {
		t.Fatal("corpus.json holds no stability cases")
	}

	for version, want := range c.Stability {
		if want == "stable" {
			want = "" // composer names the release case; Go returns empty
		}
		if got := Stability(version); got != want {
			t.Errorf("%-16s php=%-6q go=%q", version, want, got)
		}
	}
}
